@startuml
start

:Bug Arrival (Poisson Process);

:Developer Queue;
:Developer Work;

:QA Queue;
:QA Testing;

if ("Pass QA") then (yes)
  :Bug Closed;
  stop
else ("Fail QA - Rework")
  :Back to Developer Queue;
  -[back]-> :Developer Queue;
endif

@enduml